add maintenance checklist popup
Code-4-Community/green-infrastructure pull request #28
Opened 2024-09-19 03:35 UTC by ItsEricSun

### ℹ️ Issue

Closes https://www.notion.so/mahekagg/Add-Maintenance-Visit-Checklist-popup-7ddf5d74e26544cab24ebbac799223ef?pvs=4

### 📝 Description

Added a maintenance visit checklist popup when clicking on Maintenance Visit Checklist on /volunteer page.

Briefly list the changes made to the code:
1. Added a Maintenance Visit Checklist Popup component 
2. Updated VolunteerDashboard and VolunteerPage to use this new component

### ✔️ Verification

![image](https://github.com/user-attachments/assets/34647515-8cfe-451b-a0b1-2b21dbcf4b55)
![image](https://github.com/user-attachments/assets/3b5b3e20-8bc5-41ef-9a42-b9f20c53bae4)

### 🏕️ (Optional) Future Work / Notes

Clicking next currently prints the currently selected site to the console. This should be updated so the website displays the maintenance checklist for the selected site.

2024-09-22 17:20 UTC, hams7504 requested changes
Looks great, thanks Eric! All the logic makes sense and it works great! One nitpick that I have is that the font for the text and the dropdown should be styled a little more like this:
![image](https://github.com/user-attachments/assets/8c9bbb84-6b65-45de-a72c-0bbb1e04566b)
Here is a link to the figma: [figma](https://www.figma.com/design/ApMqBqNzibtOiHgOxR3AzI/Lo-fis?node-id=162-2&node-type=canvas&t=3jDCg7G7HaSThozI-0 )

2024-09-24 00:13 UTC, ItsEricSun commented
With updated fonts and style

![image](https://github.com/user-attachments/assets/30728b30-1390-464e-9f9d-922259bb02f7)
![image](https://github.com/user-attachments/assets/a136045f-80b3-4368-9bd1-e86a6235c28c)

2024-09-25 13:50 UTC, neetidesai commented
LGTM except for the warnings git flagged!

2024-09-25 13:54 UTC, neetidesai commented on apps/frontend/src/components/volunteerDashboard/MaintenanceChecklistPopup.tsx
> +            backgroundColor: '#D9D9D9',
just a thought - do we want to have standard fonts/colors for the website? they might already be somewhere that I didn't see but just a thought!

2024-09-30 22:41 UTC, hams7504 commented on apps/frontend/src/components/volunteerDashboard/MaintenanceChecklistPopup.tsx
> +            backgroundColor: '#D9D9D9',
Yea, they should be in the figma! Raaby, our designer, can also help out

2024-09-30 22:42 UTC, hams7504 approved these changes
Looks great, thank you for the changes!

2024-10-21 23:09 UTC, merged